### ISSUE TITLE
Data split error in summarize-cells

### ISSUE THREAD

**Issue by ErinWeisbart** [broadinstitute/pooled-cell-painting-profiling-recipe#96]
```
  plates:
    - Plate1
    - Plate2
  wells:
    set1:
      - Well1
    set2:
      - Well2
 ```

In the experiment.yaml I had set up a data split. The plots that were saved out during `summarize-cells` were all messed up. Some plots overwriting themselves, some only including weird amounts of data.
